export const ADMINS_FETCHED = 'admins.ADMINS_FETCHED';
export const ADMINS_FETCH_STARTED = 'admins.ADMINS_FETCH_STARTED';
export const ADMINS_FETCH_FAILED = 'admins.ADMINS_FETCH_FAILED';
export const ADMIN_CREATED = 'admins.ADMIN_CREATED';
export const ADMIN_CREATION_FAILED = 'admins.ADMIN_CREATION_FAILED';
