export const TOKEN_FETCHED = 'user.TOKEN_FETCHED';
export const TOKEN_FETCH_STARTED = 'user.TOKEN_FETCHIND_STARTED';
export const TOKEN_FETCH_FAILED = 'user.TOKEN_FETCH_FAILED';
export const TOKEN_INVALIDATED = 'user.TOKEN_INVALIDATED';
export const LOGIN_FORM_INPUT_INVALID = 'user.LOGIN_FORM_INPUT_INVALID';
